version: "3.9"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: web
    image: django-dev-devadalberto:0.0.2
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - devdb

  pgadmin:
    build: ./pgadmin
    container_name: pgadmin4
    image: pgadmin4-dev-devadalberto:0.0.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=insecurePassw0rd!
    ports:
      - "9050:80"
    restart: always
    depends_on:
      - devdb
    volumes:
      - pgadmin:/root/.pgadmin

  devdb:
    build: ./database
    container_name: devdb
    image: postgres-dev-devadalberto:0.0.2
    environment:
      - POSTGRES_USER=devpostgres
      - POSTGRES_PASSWORD=devKamehameha
      - POSTGRES_DB=devpostgres
    # env_file:
    #   - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - data-dev:/var/lib/postgresql/data

volumes:
  data-dev:
  pgadmin:
