version: '3.9'
services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: web
    image: django-dev-devadalberto:0.0.1
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  pgadmin:
    build: ./pgadmin
    container_name: pgadmin4
    image: pgadmin4-dev-devadalberto:0.0.1
    environment: 
        - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=insecurePassw0rd!
    ports:
        - '5050:80'
    restart: always
    depends_on:
      - db
    volumes: 
        - pgadmin:/root/.pgadmin
  

  db:
    build: ./database
    container_name: db
    image: postgres-dev-devadalberto:0.0.1
    environment:
      - POSTGRES_USER=dbadmindev
      - POSTGRES_PASSWORD=dbapasswd1dev
      - POSTGRES_DB=pgsqldbdev
    # env_file:
    #   - .env.dev
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
    db-data:
    pgadmin:
  